/*********************************************/
/*  AUTHOR  :   ARJUN SAPKOTA               */
/*  VERSION :   V1.0                        */
/*  APP     :   AMAZON LIKE CLI-APP         */
/*******************************************/

DROP DATABASE IF EXISTS BAMAZON;
CREATE DATABASE BAMAZON;
USE BAMAZON;
CREATE TABLE PRODUCTS (
ITEM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(20),
DEPARTMENT_NAME VARCHAR(20),
PRICE DECIMAL(10,2),
STOCK_QUANTITY INT
);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("GARLIC","PRODUCE",2.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("ONION","PRODUCE",1.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("SPINACH","PRODUCE",3.99,15);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("CLORAX","CLEANING",11.99,8);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("DETERGENT","CLEANING",12.99,7);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("MILK","DAIRY",2.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("CHEESE","DAIRY",3.50,2);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("CREAM" ,"DAIRY",1.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("ICE CREAM","DAIRY",1.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("WHITE BREAD","BAKERY",5.99,10);
INSERT INTO PRODUCTS (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY)
VALUES ("ITALIAN BISCOTTI","BAKERY",2.99,10);